### ISSUE TITLE
Better compatibility with a lower o higher version?

### ISSUE THREAD

**Issue by j0nl1** [rlindsberg/Hackintosh-On-MSI-GL62m-7REX#12]
First of all I want to thank you for this guide so well detailed. 

My question is if a lower version o the new Mojave have a better compatibility?

**Comment by rlindsberg** [comment]
Hi, this guide applies only to High Sierra 10.13.6 (17G65). Other versions have't been tested. All hardware are different so one should follow my documentation to create his/her own config.plist and kexts.
