### ISSUE TITLE
Did you get audio working?

### ISSUE THREAD

**Issue by jbwharris** [rlindsberg/Hackintosh-On-MSI-GL62m-7REX#13]
I followed your lead and published my [GL72M 7RDX build to GitHub](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX) and I thought I would see if my build might be any help for getting your audio working. I wrestled with it for quite awhile, but was able to get it working using AppleHDA Patcher 1.9. I had a little bit of instruction in my readme about it.

**Comment by rlindsberg** [comment]
Yes, I use for now VoodooHDA.kext. But the correct way is to extract hardware id and build your own audio kext.

**Comment by rlindsberg** [comment]
Lovely! I will checkout your build. Thanks for letting me know!

**Comment by jbwharris** [comment]
I was curious if you got sleep/wake to work on your machine? In your notes there was no mention of it being an issue, so I was unsure. I had someone mention that it could be impossible for some HD 630 builds, but I'm not sure I buy that. Though it does seem to be super common with anyone I've seen building with these MSI laptops.

**Comment by rlindsberg** [comment]
Sleep works, but not perfectly. Got it working after disabling my gtx 1050 ti. Upon waking up, it will automatically reenable the discrete gpu, the battery drains dramatically faster. I only use sleep when I don't care about power consumption

**Comment by jbwharris** [comment]
I was actually just able to get sleep/wake working tonight. I don't think it's enabling the second processor, but how would I be able to tell if it was?

**Comment by rlindsberg** [comment]
Oh great! Just refer to the power button. Blue light means dGPU is disabled. Red means enabled.

**Comment by rlindsberg** [comment]
Ah, I see! And great news, today I finally found out why mine turns red after sleep. I patched DSDTs and everything works like a charm! I even fixed the audio!

**Comment by jbwharris** [comment]
Are they config.plist patches, or direct DSDT patches?

**Comment by rlindsberg** [comment]
DSDT patches 😄 
Details: f72ef5d7222ac1cb714d1ca47084fd6ed78e4674

**Comment by rlindsberg** [comment]
@jbwharris I really hate Github references, every time I do a git amend or rewrite commit history to get rid of sensitive data, it shows here and never disappears
