### ISSUE TITLE
Using this guide on GL62M-7RDX

### ISSUE THREAD

**Issue by rezonated** [rlindsberg/Hackintosh-On-MSI-GL62m-7REX#23]
Hello there! First of all, thank you so much for the well-detailed guide for this laptop. I got the GL62M-7RDX model, can I use this guide for installing Mojave for my specific model? Thanks in advance, have a good day!

**Comment by jbwharris** [comment]
You might find my guide useful for my [GL72M-7RDX](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX), I believe the only real difference between yours and mine is the 15.6 and 17" screens. Mine isn't so much a step by step than a build details guide and I did use @rlindsberg's guide to help me along the way.

**Comment by rezonated** [comment]
Thanks, @jbwharris definitely will take a look on your guide, Thanks for the response and have a nice day!

**Comment by rlindsberg** [comment]
@rezonated Glad that you found my repo!

The success rate is majorly depend on your motherboard and how the DSDT table structure look like. But since you have a 7th gen CPU, the motherboard chipset is the same as my 7REX, so I think you should definitely give it a try!
