### ISSUE TITLE
Unable to boot into first install

### ISSUE THREAD

**Issue by mustang9969** [rlindsberg/Hackintosh-On-MSI-GL62m-7REX#24]
I tried building a hackintosh on my laptop setting it up to dual boot with windows using this repo and the guide mentioned in the readme from tonymacx86 as my references. I tried setting it up with Mojave and High Sierra as well but in case of Mojave it showed and stuck on a white stop sign and in case of High Sierra it just rebooted into windows. I've tried rehabman's fork of clover as well as the latest build from sourceforge. Also I tried using the kexts from both the sources mentioned above.

**Comment by rlindsberg** [comment]
Can you upload your EFI folder and I’ll take a look 😊

**Comment by mustang9969** [comment]
[EFI.zip](https://github.com/rlindsberg/Hackintosh-On-MSI-GL62m-7REX/files/3697599/EFI.zip)
I downloaded the latest version of Mac OS Mojave from the app store and tried booting but it just rebooted into windows without anything. If you wish to see, I can upload the complete contents from the Clover EFI partition of my USB drive. I'm using a Kingston USB 3.0 drive for this purpose. 
Is there any way you could indicate me to the exact folder contents I need in my clover partition?

**Comment by rlindsberg** [comment]
Thank you for describing your installation progress and providing info about USB 3.0 drive. However, I need to know your motherboard model, CPU model and (if any) dedicated GPU model. If you don't know, provide your laptop model name might help to figure out.

Here, you disabled Nvidia GPU:
![Screen Shot 2019-10-07 at 8 47 29 PM](https://user-images.githubusercontent.com/2918707/66339898-64d15880-e944-11e9-9ba1-78c3bbf402c5.png)

But you tell macOS to use Nvidia, which could be the reason it won't boot.
![Screen Shot 2019-10-07 at 8 48 47 PM](https://user-images.githubusercontent.com/2918707/66339907-67cc4900-e944-11e9-83e5-43d4a85c356e.png)

And you left SMBIOS empty... choose one depending your CPU
![Screen Shot 2019-10-07 at 8 51 45 PM](https://user-images.githubusercontent.com/2918707/66339909-69960c80-e944-11e9-8480-c01b3c4c2812.png)

**Comment by rlindsberg** [comment]
> If you wish to see, I can upload the complete contents from the Clover EFI partition of my USB drive.

Your current EFI provides just enough information about your Clover config 👍 


> I'm using a Kingston USB 3.0 drive for this purpose.

According to RehabMan, USB 2.0 has better compatibility. But since your Clover config is wrong, let's try USB 2.0 at the very last.

**Comment by mustang9969** [comment]
I am currently using MSI GL62M 7REX laptop with i7-7700hq CPU and Nvidia GTX 1050ti dedicated GPU.

**Comment by mustang9969** [comment]
Can you please edit the contents of the config because somehow my xcode isn't working. I will provide all the details required. Also I wanted to make sure that getting the most recent version of Mojave wasn't causing problems.

**Comment by mustang9969** [comment]
What software are you using to edit config.plist file?
Sorry if this sounds dumb but I'm really new to hackintoshing

**Comment by rlindsberg** [comment]
Try this and come back with update about how it went :)

[config.plist.zip](https://github.com/rlindsberg/Hackintosh-On-MSI-GL62m-7REX/files/3701741/config.plist.zip)

I use Xcode due to RehabMan's recommendation.

**Comment by mustang9969** [comment]
> Try this and come back with update about how it went :)
> 
> [config.plist.zip](https://github.com/rlindsberg/Hackintosh-On-MSI-GL62m-7REX/files/3701741/config.plist.zip)

I tried with this file but still it's panicking and restarting into windows showing nothing.
I'm attaching the current EFI folder and the version of macOS I'm trying to install is 10.14.6
[EFI.zip](https://github.com/rlindsberg/Hackintosh-On-MSI-GL62m-7REX/files/3706313/EFI.zip)

**Comment by rlindsberg** [comment]
I need pictures about the verbose output in order to diagnose..

**Comment by jbwharris** [comment]
I feel like part of your problem is trying to install around Windows. If you have 2 hard drives in this laptop I'd recommend pulling the the Windows drive out and dealing only with the Mac drive until you have things sorted out. Having them on separate drives will make your life a lot easier. I roughly [outlined my process for installing Windows and Ubuntu](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX) on my build.

**Comment by mustang9969** [comment]
> I need pictures about the verbose output in order to diagnose..

I could grab this only, and also I am not able to get the complete logs for the verbose installation
![IMG_20191010_214658](https://user-images.githubusercontent.com/56058297/66587786-bda12b00-eba8-11e9-98b8-e26cb73360ac.jpeg)

Also if there's a way to grab a complete log of the verbose install please do tell.


> I feel like part of your problem is trying to install around Windows. If you have 2 hard drives in this laptop I'd recommend pulling the the Windows drive out and dealing only with the Mac drive until you have things sorted out. Having them on separate drives will make your life a lot easier. I roughly [outlined my process for installing Windows and Ubuntu](https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX) on my build.

I just clicked on the install button in clover, I never saw the option to select the drive. I am planning to install Mojave on my HDD leaving the windows partition in my SSD intact.  
Also I read somewhere that the kernel panic didn't occur with a USB 2.0 drive so I'm going to try that  as well but still I want to know where I'm going wrong. I have intel usb controllers for the 3.0 ports.

**Comment by rlindsberg** [comment]
Try these:
[EFI.zip](https://github.com/rlindsberg/Hackintosh-On-MSI-GL62m-7REX/files/3713850/EFI.zip)

[EFI 2.zip](https://github.com/rlindsberg/Hackintosh-On-MSI-GL62m-7REX/files/3713865/EFI.2.zip)

**Comment by rlindsberg** [comment]
As far as I know, there is only possible to dump boot log once you have entered macOS. So I will tell after you succeed installing macOS 🎉 🥂

**Comment by mustang9969** [comment]
I tried both of these but got the same result

**Comment by mustang9969** [comment]
I'm probably going to try installing via a USB 2.0 drive hoping that Mojave fits on an 8 gig drive

**Comment by rlindsberg** [comment]
I just read a thread written by RehabMan that kernel panik (what you have right now) is related to graphics pre-allocated memory.. so it might not help with USB 2.0 either.

Can you post a thread here? https://www.tonymacx86.com/forums/mojave-laptop-support.196/

There are many helpful people who are more confident in Hackintosh than me there. Hopefully your issue will be resolved within days!

**Comment by rlindsberg** [comment]
Closed due to inactivity
