### ISSUE TITLE
Thanks for the EFI

### ISSUE THREAD

**Issue by FahrilPratama** [rlindsberg/Hackintosh-On-MSI-GL62m-7REX#25]
Halo
I want to ask for help
What the spesific patch that you use? because im a newbie in hackintosh
I want to learn how to patch my MSI GL62M 7REX
I want to use Hackintosh Mojave 10.14.6

Thank you very much

**Comment by rlindsberg** [comment]
Hi,

I do not understand what you mean by "patch".

I suggest you read more tutorials about hackintosh on https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/

to learn more about how it works. You are welcome to ask questions here after you got familiar with the terms and names the hackintosh community uses.
